# Generated by Django 5.2.1 on 2025-05-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_id'),
        ('routes', '0001_initial'),
        ('trains', '0002_alter_train_id_alter_traintest_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['travel_time'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.RemoveField(
            model_name='route',
            name='travel_times',
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='route',
            name='travel_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total travel time'),
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='route',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_from_city_set', to='cities.city', verbose_name='From city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to_city_set', to='cities.city', verbose_name='To city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='trains',
            field=models.ManyToManyField(to='trains.train', verbose_name='Train list'),
        ),
    ]
