# Generated by Django 5.2.1 on 2025-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_options_remove_route_travel_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='route',
            name='travel_time',
            field=models.PositiveSmallIntegerField(verbose_name='Total travel time'),
        ),
    ]
